version: '3.8'

services:
  # Certbot для автоматического обновления SSL сертификатов
  certbot:
    image: certbot/certbot
    container_name: ytorsweb_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email --domains ${DOMAIN},www.${DOMAIN}
    depends_on:
      - nginx

  # Cron для автоматического обновления сертификатов
  certbot-renew:
    image: certbot/certbot
    container_name: ytorsweb_certbot_renew
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
